      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true
          depth: 1

      - name: Pull git submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3 python3-pip python3-setuptools python3-dev rsync unzip wget zlib1g-dev

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate .config
        run: |
          echo "CONFIG_TARGET_qualcommax=y" > .config
          echo "CONFIG_TARGET_qualcommax_ipq807x=y" >> .config
          echo "CONFIG_TARGET_MULTI_PROFILE=y" >> .config
          echo "CONFIG_TARGET_DEVICE_qualcommax_ipq807x_xiaomi_ax3600-bigpart=y" >> .config
          
          # 只保留基础包，删掉VIKINGYFY那一堆NSS私有CONFIG！
          echo "CONFIG_PACKAGE_kmod-qca-nss-drv=y" >> .config
          echo "CONFIG_PACKAGE_kmod-qca-nss-ecm=y" >> .config
          echo "CONFIG_PACKAGE_kmod-qca-nss-dp=y" >> .config
          echo "CONFIG_PACKAGE_kmod-qca-nss-clients=y" >> .config
          echo "CONFIG_PACKAGE_nss-firmware-ipq807x=y" >> .config
          
          echo "CONFIG_PACKAGE_kmod-ath11k=y" >> .config
          echo "CONFIG_PACKAGE_wpad-full=y" >> .config
          echo "CONFIG_PACKAGE_ipq-wifi-xiaomi_ax3600=m" >> .config
          
          echo "CONFIG_PACKAGE_luci=y" >> .config
          echo "CONFIG_PACKAGE_luci-base=y" >> .config
          echo "CONFIG_PACKAGE_luci-mod-admin-full=y" >> .config
          echo "CONFIG_PACKAGE_luci-theme-bootstrap=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-firewall=y" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-base-zh-cn=y" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y" >> .config
          
          echo "CONFIG_PACKAGE_dnsmasq-full=y" >> .config
          echo "CONFIG_PACKAGE_dropbear=y" >> .config
          echo "CONFIG_PACKAGE_firewall4=y" >> .config
          echo "CONFIG_PACKAGE_htop=y" >> .config
          
          echo "# CONFIG_PACKAGE_kmod-shortcut-fe is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-shortcut-fe-cm is not set" >> .config
          make defconfig
          sed -i 's/CONFIG_PACKAGE_kmod-shortcut-fe=y/# CONFIG_PACKAGE_kmod-shortcut-fe is not set/g' .config
          sed -i 's/CONFIG_PACKAGE_kmod-shortcut-fe-cm=y/# CONFIG_PACKAGE_kmod-shortcut-fe-cm is not set/g' .config

      - name: Compile firmware
        run: make -j1 V=s
